### ISSUE TITLE
AuthCubit close when app still using

### ISSUE THREAD

**Issue by quydn720** [fikretsengul/flutter_advanced_boilerplate#12]
When users log in successfully, AuthCubit automatically closes. Then if the user presses the logout icon button, then we have the error: Bad state: Cannot emit new states after calling close. I wonder if there are any problems with the auto_route package.

**Comment by fikretsengul** [comment]
I noticed that too. An update is coming with various improvements.

**Comment by fikretsengul** [comment]
The new version released [check it out](https://github.com/fikretsengul/flutter_advanced_boilerplate/blob/main/CHANGELOG.md).
