### ISSUE TITLE
Theme is Persisted on Disk

### ISSUE THREAD

**Issue by anlumo** [fikretsengul/flutter_advanced_boilerplate#18]
The `AppState` class contains the app theme and is used in `AppCubit`, which is a `HydratedCubit`. This causes the theme to be persisted into the hydrated storage.

This means that after the application is run for the first time, it's not possible to adjust the theme any more, because it's loaded from disk rather than using the new definition.

This would be fine for development (just `rm ~/Documents/hydrated_box.*` to reset the state), but this would also stop app updates from changing the theme on the users' computers, which is bad.

**Comment by fikretsengul** [comment]
I'll look at it and will tell you about the details.

**Comment by fikretsengul** [comment]
Sorry for being late but nowadays I'm too busy because of the work. I'm planning to cover current issues on this weekend. So sorry for the delay. @anlumo

**Comment by fikretsengul** [comment]
Hello everyone (@anlumo) again after a long break,

I am sorry that the new version is so late. During the time we were apart, I did my military service and got married.

Of course, I have gained a lot of knowledge and experience during this time. Thanks to these gains, Flutter Advanced Boilerplate is now up-to-date, better quality, more performant, more modular and easier to use.

You can experience these exciting improvements by upgrading to [v2.0.0-alpha](https://github.com/fikretsengul/flutter_advanced_boilerplate/tree/v2.0.0-alpha), which has just started testing, and start sharing any issues you find with me.

More exciting developments and news are on the way. Stay tuned.
