### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by jangopper** [fikretsengul/flutter_advanced_boilerplate#19]
I like it! :)
Minor issue:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Develop\Flutter\Playground\Boilerplates\flutter_advanced_boilerplate-main\android\app\build.gradle' line:
 29
 AND
 * Where:
Build file 'C:\Develop\Flutter\Playground\Boilerplates\flutter_advanced_boilerplate-main\android\app\build.gradle' line:
 50
 
Fixed by adding (in my instance) the following two lines to flutter_advanced_boilerplate\android\local.properties:
flutter.compileSdkVersion=33
flutter.minSdkVersion=26

Please add to "How To Use" section.

Thank you for this!

**Comment by fikretsengul** [comment]
It should already be there but I'll be checking it.

**Comment by fikretsengul** [comment]
Sorry for being late but nowadays I'm too busy because of the work. I'm planning to cover current issues on this weekend. So sorry for the delay. @jangopper
