### ISSUE TITLE
`strings.g.dart` not being generated

### ISSUE THREAD

**Issue by satvikpendem** [fikretsengul/flutter_advanced_boilerplate#20]
I cloned the repo and followed the instructions, but `package:flutter_advanced_boilerplate/i18n/strings.g.dart` is still not being generated even though I ran `flutter packages pub run build_runner build -d`. So I can't run the app at all.

**Comment by LiorAgnin** [comment]
@satvikpendem I had the issue, but I found that I didn't flow the instructions correctly. 
Did you run also: `flutter pub run slang`? Look at the [build section](https://github.com/fikretsengul/flutter_advanced_boilerplate#hammer-build)

**Comment by satvikpendem** [comment]
You're right, I didn't read the build section properly. Works now.
