### ISSUE TITLE
Android studio & vscode behavior weirdly with this project. 

### ISSUE THREAD

**Issue by Abdullah-Arab** [fikretsengul/flutter_advanced_boilerplate#25]
Android studio & vscode is not analyzing this project probably they cannot find the start and the end of any widget and they cannot reveal the source of any object or widget when I press cmd and click on a specific object

**Comment by fikretsengul** [comment]
Please be sure that you've executed these commands in a row:

`# Install dependencies
$ flutter pub get

# Generate structured language files
$ flutter pub run slang

# Checks missing and unused translations
$ flutter pub run slang analyze

# Generate data classes & structured asset files
$ flutter packages pub run build_runner build -d`

and also provide some explanation in addition to screenshots.
