### ISSUE TITLE
injectable_generator:injectable_builder error

### ISSUE THREAD

**Issue by nkrmr** [fikretsengul/flutter_advanced_boilerplate#34]
Hi,

I have this error when I tried to launch the app 

<img width="1088" alt="Screenshot 2023-05-31 at 16 26 35" src="https://github.com/fikretsengul/flutter_advanced_boilerplate/assets/686395/1cf00b5d-4963-486d-8af5-5b3ad190e4d3">

My Flutter config is

<img width="819" alt="Screenshot 2023-05-31 at 16 27 16" src="https://github.com/fikretsengul/flutter_advanced_boilerplate/assets/686395/045951c6-bd2c-4919-b3a9-ba0a592dbfb8">

I'm on Mac os 13.4

Do you have any idea what's going on?

Best regards,

**Comment by sauravgurjar** [comment]
same issue

**Comment by fikretsengul** [comment]
New version which is 1.0.0+6 is on the way. You can check and use ['stage'](https://github.com/fikretsengul/flutter_advanced_boilerplate/tree/stage) branch until completing all other updates, bug fixes and merging to main. [Here is the change log (other updates on the way stay tuned)](https://github.com/fikretsengul/flutter_advanced_boilerplate/blob/stage/CHANGELOG.md) @sauravgurjar
