### ISSUE TITLE
Sample project using the boilerplate

### ISSUE THREAD

**Issue by dreadedhamish** [fikretsengul/flutter_advanced_boilerplate#4]
I'm new to opinionated boilerplates but from work in parallel fields I can see I'll benefit greatly from such structure in the future.

Could you provide a sample app? I'd like to see how to structure an app that takes advantage of (and doesn't butcher) the segmentation provided by the boilerplate. 

Edit: Unless it's meant to be a functional app as is - the code looks like it should at least have a few pages, but all I get after following the instructions and firing it up on Chrome I get stuck on the splash screen.

**Comment by dreadedhamish** [comment]
Unless it's meant to be a functional app as is - the code looks like it should at least have a few pages, but all I get after following the instructions and firing it up on Chrome is a big "</>" in the middle of the page.

**Comment by dreadedhamish** [comment]
Okay - so there should be a splash screen then login. 
Debugging in chrome stalls at the splash screen.

I have 1 test error in my console - missing plugin exception for flutter_secure_storage. I have the latest flutter_secure_storage installed - confirmed the files are on my drive and vscode doesn't throw an error referencing it. Seems that plugin has has heaps of issues - mostly with Android but also using the -web implementation.

00:37 +9: /Volumes/Data-new/GoogleDrive/code/flutter_advanced_boilerplate/test/features/auth/login/golden/login_screen_golden_test.dart: Login Golden Test Custom
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method read on channel
plugins.it_nomads.com/flutter_secure_storage)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Custom

**Comment by fikretsengul** [comment]
Of course, the boilerplate has its own examples. You should run the app on mobile iOS or android. It wasn't supported web but I'll be adding web support today. Until then you can use it on mobile.

**Comment by dreadedhamish** [comment]
Great! I've learned a LOT just browsing through it trying to get it working - I can picture most of the pages already although I've never actually seen them.
I'm primarily developing for web - so great news support is imminent. My next troubleshooting stop was setting up a device for testing.

**Comment by fikretsengul** [comment]
The new version released [check it out](https://github.com/fikretsengul/flutter_advanced_boilerplate/blob/main/CHANGELOG.md).
