### ISSUE TITLE
FlutterSecureStorage is not registered inside GetIt

### ISSUE THREAD

**Issue by faizsk11** [fikretsengul/flutter_advanced_boilerplate#5]
Exception has occurred.
_AssertionError ('package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type FlutterSecureStorage is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?))

**Comment by fikretsengul** [comment]
Can you provide more details about the flow?

**Comment by fikretsengul** [comment]
The new version released [check it out](https://github.com/fikretsengul/flutter_advanced_boilerplate/blob/main/CHANGELOG.md).

**Comment by faizsk11** [comment]
Thank you
