### ISSUE TITLE
Login screen - takes hitting tab twice to move to password field on web

### ISSUE THREAD

**Issue by dreadedhamish** [fikretsengul/flutter_advanced_boilerplate#9]
A little issue - using Chrome - after entering the username if you hit tab once it will select the password field (slight change of colour) but you need to hit tab again for it to actually give you a text interface.

**Comment by fikretsengul** [comment]
Thank you. I'll be checking that.

**Comment by fikretsengul** [comment]
The new version released [check it out](https://github.com/fikretsengul/flutter_advanced_boilerplate/blob/main/CHANGELOG.md).
